### ISSUE TITLE
how to reduce time when we use vulcan to blur

### ISSUE THREAD

**Issue by 1280149014** [android/renderscript-samples#18]
I find a bug in the demo,   which compare renderscript ,  renderscriptInstrinct, Vulcan . 
The way you calculate time， Only include render time 。
if we  calculate time include render time and parpare time ，  I find that renderscriptInstrinct is the fastest way to blur。  
Can  we reduce the parpare time  when we use Vulcan blur

**Comment by Kottsone** [comment]
In my opinion, it is not fair to compare the Vulkan performance, either prepare or render time, with RenderScript Intrinsics, because intrinsics are highly optimized for a specific task (so that it can be pre-compiled and pre-tuned), while Vulkan is generic and programmable. Vulkan vs RenderScript custom scripts is a fairer comparison, I think.

In general, when using Vulkan, you should avoid paying the preparation cost every time when you just want to execute the kernel -- consider having everything prepared early in the application if possible. There are some techniques to reduce the Vulkan preparation time, e.g. using pipeline cache to reduce the pipeline creation cost, but that really depends on the actual usage pattern. Alternatively, please also see https://github.com/android/renderscript-intrinsics-replacement-toolkit for CPU intrinsics kernels.
